### ISSUE TITLE
Couldnt connect to Jupyter Notebook

### ISSUE THREAD

**Issue by majlucaaa** [fanz-xlnx/Adapt_Workshop_VAI101#1]
Hello, Ive followed all the steps to begin the Workshop but sadly I am still not able to connect to the Jupyter notebook even though I am putting my IP... is it possible that you publish the content of the notebook here?

**Comment by fanz-amd** [comment]
The Jupyter notebook contains both instructions and command lines, have you modified the jupyter_notebook_config.py to allow external access?

**Comment by majlucaaa** [comment]
Yes, I have changed line 210 so that it is c.NotebookApp.ip=‘*’, save and then when i write “jupiter notebook” the link still starts with “https://localhost:8888…” and when I try to change the link by hand so that it is “https://ip-myPublicIP:888…” still the notebook is not opening. I’ve also tried to run  “jupyter notebook -- ip 0.0.0.0” and instead of localhost there is another ip but still not working

**Comment by fanz-amd** [comment]
Please remove "ip-". The link should be something like "http://xxx.xxx.xxx.xxx:8888...."

**Comment by majlucaaa** [comment]
![image](https://user-images.githubusercontent.com/82088688/132628893-d22d459e-12f8-4a90-8b94-af7e8c1c411f.png)
![image](https://user-images.githubusercontent.com/82088688/132628968-3a0abe67-4d09-492c-8c69-32a808641ede.png)
![image](https://user-images.githubusercontent.com/82088688/132629130-d09b6ea4-20ee-4524-8d27-211cda31bdbb.png)

Here are some images. I am user2006 and when I put this on Chrome "http://54.202.236.203:8888/?token=9acf2022bfe8e29d5abd66afaa6c5aad0c6d00e31ab96b61" it is not opening

**Comment by fanz-amd** [comment]
The line 210 is still comments out. please remove the pound sign at beginning.

**Comment by majlucaaa** [comment]
Omg, I totally didnt see it. Thank you so much!
